//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using L2Sql.DomainModel;
    
    public partial class LogqsoDataEntities : DbContext
    {
        public LogqsoDataEntities()
            : base("name=LogqsoDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<CabrilloInfo> CabrilloInfoes { get; set; }
        public virtual DbSet<CallInfo> CallInfoes { get; set; }
        public virtual DbSet<CallSign> CallSigns { get; set; }
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<ContestType> ContestTypes { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LogCategory> LogCategories { get; set; }
        public virtual DbSet<Qso> Qsoes { get; set; }
        public virtual DbSet<QsoExchangeAlpha> QsoExchangeAlphas { get; set; }
        public virtual DbSet<QsoExchangeType> QsoExchangeTypes { get; set; }
        public virtual DbSet<QsoExtraData> QsoExtraDatas { get; set; }
        public virtual DbSet<QsoModeType> QsoModeTypes { get; set; }
        public virtual DbSet<QsoRadioType> QsoRadioTypes { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<UbnDupe> UbnDupes { get; set; }
        public virtual DbSet<UbnIncorrectCall> UbnIncorrectCalls { get; set; }
        public virtual DbSet<UbnIncorrectExchange> UbnIncorrectExchanges { get; set; }
        public virtual DbSet<UbnNotInLog> UbnNotInLogs { get; set; }
        public virtual DbSet<UbnSummary> UbnSummaries { get; set; }
        public virtual DbSet<UbnUnique> UbnUniques { get; set; }
    }
}
