//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class CallInfo : IEntity
    {
        public int LogId { get; set; }
        public string StationName { get; set; }
        public int CallInfoId { get; set; }
        public int CallGroup { get; set; }
        public string UserName { get; set; }
        public string ContestId { get; set; }
        public int CallsignId { get; set; }
        public string SessionName { get; set; }
        public bool Disabled { get; set; }
        public Logqso.mvc.common.Enum.QsoRadioTypeEnum QsoRadioTypeEnum { get; set; }
        public EntityState EntityState { get; set; }
    
        public virtual CallSign CallSign { get; set; }
        public virtual Contest Contest { get; set; }
        public virtual QsoRadioType QsoRadioType { get; set; }
        public virtual Session Session { get; set; }
        public virtual Station Station { get; set; }
    }
}
