//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class ContestType : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContestType()
        {
            this.Contests = new HashSet<Contest>();
        }
    
        public Logqso.mvc.common.Enum.ContestTypeEnum ContestTypeEnum { get; set; }
        public string ContestTypeEnumName { get; set; }
        public Logqso.mvc.common.Enum.QsoExchangeTypeEnum QsoExchangeTypeEnum { get; set; }
        public string QsoExchangeName { get; set; }
        public string QsoMultName { get; set; }
        public string QsoMult2Name { get; set; }
        public string ExtraDataName { get; set; }

        public EntityState EntityState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contest> Contests { get; set; }
        public virtual QsoExchangeType QsoExchangeType { get; set; }
    }
}
