//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class Log : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Log()
        {
            this.Qsoes = new HashSet<Qso>();
            this.Stations = new HashSet<Station>();
        }
    
        public int LogId { get; set; }
        public System.DateTime ContestYear { get; set; }
        public int CallsignId { get; set; }
        public string ContestId { get; set; }
        public int LogCategoryId { get; set; }
        public Nullable<short> QsoExchangeNumber { get; set; }
        public string QsoDatabaseServerInstance { get; set; }
        public string QsoDatabaseInstance { get; set; }
        public string QsoDatabaseTableName { get; set; }
        public Nullable<int> WintestDataID { get; set; }
        public Nullable<int> N1mmDataID { get; set; }
        public EntityState EntityState { get; set; }
    
        public virtual CallSign CallSign { get; set; }
        public virtual Contest Contest { get; set; }
        public virtual LogCategory LogCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qso> Qsoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station> Stations { get; set; }
    }
}
