//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCategory : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogCategory()
        {
            this.Logs = new HashSet<Log>();
            this.UbnSummaries = new HashSet<UbnSummary>();
        }
    
        public int LogCategoryId { get; set; }
        public Logqso.mvc.common.Enum.CatOperatorEnum CatOperatorEnum { get; set; }
        public Logqso.mvc.common.Enum.CatOperatorOverlayEnum CatOperatorOverlayEnum { get; set; }
        public Logqso.mvc.common.Enum.CatBandEnum CatBandEnum { get; set; }
        public Logqso.mvc.common.Enum.CatPowerEnum CatPowerEnum { get; set; }
        public Logqso.mvc.common.Enum.CatAssistedEnum CatAssistedEnum { get; set; }
        public Logqso.mvc.common.Enum.CatNoOfTxEnum CatNoOfTxEnum { get; set; }

        public EntityState EntityState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbnSummary> UbnSummaries { get; set; }
    }
}
