//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class Qso : IEntity
    {
        public short QsoNo { get; set; }
        public int LogId { get; set; }
        public string StationName { get; set; }
        public decimal Frequency { get; set; }
        public int CallsignId { get; set; }
        public System.DateTime QsoDateTime { get; set; }
        public short RxRst { get; set; }
        public short TxRst { get; set; }
        public Nullable<short> QsoExchangeNumber { get; set; }
        public Logqso.mvc.common.Enum.QsoModeTypeEnum QsoModeTypeEnum { get; set; }
        public Logqso.mvc.common.Enum.QsoRadioTypeEnum QsoRadioTypeEnum { get; set; }
        public EntityState EntityState { get; set; }
    
        public virtual CallSign CallSign { get; set; }
        public virtual Log Log { get; set; }
        public virtual QsoModeType QsoModeType { get; set; }
        public virtual QsoRadioType QsoRadioType { get; set; }
        public virtual Station Station { get; set; }
        public virtual QsoExchangeAlpha QsoExchangeAlpha { get; set; }
        public virtual QsoExtraData QsoExtraData { get; set; }
    }
}
