//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class Session : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.CallInfoes = new HashSet<CallInfo>();
        }
    
        public string SessionName { get; set; }
        public string UserName { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public string CategorySettings { get; set; }
        public string FiltersSettings { get; set; }
        public string XaxisSettings { get; set; }
        public string YaxisSettings { get; set; }
        public Nullable<decimal> Subscription { get; set; }
        public EntityState EntityState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallInfo> CallInfoes { get; set; }
    }
}
