//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class Spot : IEntity
    {
        public int SpotId { get; set; }
        public string ContestId { get; set; }
        public int CallSignId { get; set; }
        public int SpoterCallSignId { get; set; }
        public System.DateTime SpotDateTime { get; set; }
        public decimal Frequency { get; set; }
        public EntityState EntityState { get; set; }
    
        public virtual CallSign CallSign { get; set; }
        public virtual CallSign CallSign1 { get; set; }
        public virtual Contest Contest { get; set; }
    }
}
