//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2Sql.DomainModel
{
    using System;
    using System.Collections.Generic;

    public partial class UbnSummary : IEntity
    {
        public int CallsignId { get; set; }
        public string ContestId { get; set; }
        public System.DateTime ContestYear { get; set; }
        public int LogCategoryId { get; set; }

        public EntityState EntityState { get; set; }
    
        public virtual CallSign CallSign { get; set; }
        public virtual Contest Contest { get; set; }
        public virtual LogCategory LogCategory { get; set; }
    }
}
